// Generated by https://quicktype.io

import { IMacroPayer } from "./payer";
import { IMacroProduct } from "./product";
import { IMacroResult } from "./result";

export interface IMacroPayment {
  transaccionId: number;
  estado: string;
  fecha: string;
  moneda: string;
  monto: string;
  productos: string;
  metodoPago: string;
  sucursal: string;
  medioPagoId: string;
  medioPagoNombre: string;
  medioPago: string;
  transaccionComercioId: string;
  estadoId: number;
  cuotas: number;
  userId: null;
  bancoId: null;
  tipoPago: null;
  informacion: null;
  montoBruto: number;
  montoDescuento: number | null;
  result: IMacroResult;
  informacionAdicional: null;
  informacionAdicionalLink: null;
  productoTransaccion: IMacroProduct[];
  informacionPagador: IMacroPayer;
  fechaPago: string;
  detalle: string;
}
