import { IMercadopagoAditionalInfo } from "./aditionalInfo";
import { IMercadopagoCard } from "./card";
import { IMercadopagoChargesDetail } from "./chargeDetail";
import { IMercadopagoFeeDetail } from "./feeDetail";
import { IMercadopagoPayer } from "./payer";
import { IMercadopagoPointOfInteraction } from "./pointOfInteraction";
import { IMercadopagoTransactionDetails } from "./transactionDetails";
export interface IMercadopagoPayment {
  acquirer_reconciliation: any[];
  additional_info: IMercadopagoAditionalInfo;
  authorization_code: string;
  binary_mode: boolean;
  brand_id: string | null;
  call_for_authorize_id: string | null;
  captured: boolean;
  card: IMercadopagoCard;
  charges_details: IMercadopagoChargesDetail[];
  collector_id: number;
  corporation_id: string | null;
  counter_currency: number | null;
  coupon_amount: number;
  currency_id: string;
  date_approved: Date;
  date_created: Date;
  date_last_updated: Date;
  date_of_expiration: Date;
  deduction_schema: string;
  description: string;
  differential_pricing_id: string;
  external_reference: string;
  fee_details: IMercadopagoFeeDetail[];
  id: number;
  installments: number;
  integrator_id: string;
  issuer_id: string | number;
  live_mode: boolean;
  marketplace_owner: string;
  merchant_account_id: string;
  merchant_number: number;
  metadata: any;
  money_release_date: Date;
  money_release_schema: string;
  notification_url: string;
  operation_type: string;
  order: any;
  payer: IMercadopagoPayer;
  payment_method_id: string;
  payment_type_id: string;
  platform_id: null;
  point_of_interaction: IMercadopagoPointOfInteraction;
  pos_id: string | null;
  processing_mode: string;
  refunds: any[];
  shipping_amount: number;
  sponsor_id: string | null;
  statement_descriptor: string;
  status: string;
  status_detail: string;
  store_id: string | null;
  taxes_amount: number;
  transaction_amount: number;
  transaction_amount_refunded: number;
  transaction_details: IMercadopagoTransactionDetails;
}
